name       : xfce4-power-manager
version    : 4.18.0
release    : 2
source     :
    - https://archive.xfce.org/xfce/4.18/src/xfce4-power-manager-4.18.0.tar.bz2 : 2eee467886252f9fa704c978ec67dafad5274ede93e59b092a688faa7e72c39a
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Power Manager for Xfce.
description: |
    Power Manager for Xfce.
builddeps  :
    - pkgconfig(libnotify)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfce4panel-2.0)
    - pkgconfig(upower-glib)
setup      : |
    %configure \
        --enable-polkit \
        --disable-debug \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
